#!/usr/bin/env ruby
# frozen_string_literal: true

# generate-ble-names.rb <data-dir> <output-file>
#
# Reads service_uuids.json, characteristic_uuids.json, descriptor_uuids.json
# from <data-dir>, filters to source=="gss" (Bluetooth SIG official) entries,
# and writes a Swift source file with three static dictionaries into <output-file>.

require "json"

abort "Usage: generate-ble-names.rb <data-dir> <output-file>" unless ARGV.length == 2

data_dir    = ARGV[0]
output_file = ARGV[1]

def load_gss(path)
  raw = JSON.parse(File.read(path))
  # Use a hash to deduplicate by UUID (last entry wins, matching JSON semantics).
  pairs = {}
  raw.select { |e| e["source"] == "gss" }
     .each { |e| pairs[e["uuid"].upcase] = e["name"] }
  pairs.sort_by { |uuid, _| uuid }
end

services        = load_gss(File.join(data_dir, "service_uuids.json"))
characteristics = load_gss(File.join(data_dir, "characteristic_uuids.json"))
descriptors     = load_gss(File.join(data_dir, "descriptor_uuids.json"))

def escape(str)
  str.gsub("\\", "\\\\").gsub('"', '\\"')
end

def dict_literal(pairs)
  return "    static let _ = [String: String]()" if pairs.empty?

  lines = pairs.map { |uuid, name| "        \"#{uuid}\": \"#{escape(name)}\"" }
  "[\n#{lines.join(",\n")}\n    ]"
end

output = <<~SWIFT
  // BLENames.generated.swift
  // Auto-generated by Scripts/generate-ble-names.rb from the Bluetooth SIG Assigned Numbers.
  // Source: https://github.com/NordicSemiconductor/bluetooth-numbers-database
  // Do not edit manually -- rebuild to regenerate.

  enum BLENameData {
      static let services: [String: String] = #{dict_literal(services)}

      static let characteristics: [String: String] = #{dict_literal(characteristics)}

      static let descriptors: [String: String] = #{dict_literal(descriptors)}
  }
SWIFT

File.write(output_file, output)
$stderr.puts "Generated #{output_file} (#{services.length} services, #{characteristics.length} characteristics, #{descriptors.length} descriptors)"
